#!/bin/bash
exec 1> >(logger --size 64k -s -t $(basename $0)) 2>&1

iwlist wlan0 scan | grep -i -E "SSID|Address|Frequency|Signal|Quality"| awk '{gsub(/^[ \t]+/,"",$0);print $0}' ORS=','




iwlist wlan0 scan | grep -i -E "SSID|Channel|Frequency|Signal|Quality|IEEE"

iwlist wlan0 scan | grep -i -E "SSID|Channel|Frequency|Signal|Quality" | awk '{print $1}' ORS=',' 2>&1 | logger -S 64k -t wifi

iwlist wlan0 scan | grep -i -E "SSID|Address|Frequency|Signal|Quality"| awk '{gsub(/^[ \t]+/,"",$0);print $0}' ORS=','


iwlist wlan0 scan | grep -i -E "SSID|Address|Frequency|Signal|Quality" 2>&1 | awk '{gsub(/^[ \t]+/,"",$0);printf "," $0}' 2>&1| logger -S 64k -t wifi
